### ISSUE TITLE
PXD-2066 ⁃ fix help for configure: example shows 'creds' flag instead of 'cred'

### ISSUE THREAD

**Issue by cgmeyer** [uc-cdis/cdis-data-client#25]
[~/Documents/Notes/gen3/gen3-client$ ./gen3-client configure
Error: required flag(s) "cred" not set
Usage:
  gen3-client configure [flags]

**Examples:
./gen3-client configure --profile=user1 --creds creds.json**

Flags:
      --cred string   Specify the credential file that you want to use
  -h, --help          help for configure

Global Flags:
      --profile string   Specify profile to add or edit with --profile user2 (default "default")

**Comment by tshao87** [comment]
has been fixed in #32
